### ISSUE TITLE
Modifications for integration in l2rpn-baselines

### ISSUE THREAD

**Issue by BDonnot** [KishanGitASU/A3C-RL-baseline-agent-for-Grid2Op-environment#1]
Hello, 

I have a few comments for the integration in the l2rpn-baselines, i will probably have some later on too ;-)

The first one is the name of your baseline, as of now it is called:
```python
from l2rpn_baselines.Multithreading_agent.ActorCritic_Agent import ActorCritic_Agent
```
But as you might have noticed:
- python names are "CamelCase" convention (at least for the exported class) so it would be nice to respect that (no underscore, uppercase at begining of words see [Camel Case](https://en.wikipedia.org/wiki/Camel_case>) on wikipedia for example). This is cosmetics but for exported class i think it's better :-)
- there is a name mismatch. If you name your Baseline `Multithreading_agent` then the name of the imported class should also be `Multithreading_agent` (and not `ActorCritic_Agent`) [see the example `from l2rpn_baselines.MyContrib.MyContrib import MyContrib`]
- name of the baseline is itself a bit ambiguous. There tons of MultiThreading agent (A2C for example) so probably you might give a more personalized name, for example Geirina named their agent Geirina, or the Uni Kassel team named it "PandapowerOPFAgent" which is super explicit imho

The package cannot be imported once integrated in the baseline. 
My recommendation would be to:
- clone the l2rpn-baselines repository (`git clone https://github.com/rte-france/l2rpn-baselines.git`)
- cd in the repo (`cd l2rpn-baselines`)
- set up an empty virtual env (`python -m virtualenv venv; source venv/bin/activate`)
- install l2rpn-balines from sources  (`pip install -e .`) and don't install anything else
- copy paste your actual repo in l2rpn_baselines (`cp -R ../A3C-RL-baseline-agent-for-Grid2Op-environment l2rpn_baselines/Multithreading_agent`)
- try to import it from python:
```python
from l2rpn_baselines.Multithreading_agent.ActorCritic_Agent import ActorCritic_Agent
from l2rpn_baselines.Multithreading_agent.ActorCritic_Agent import evaluate
```
These two should work out of the box

Once its working, copy paste back the content of `l2rpn_baselines/A3C-RL-baseline-agent-for-Grid2Op-environment` into your development github repository:
`cp -R l2rpn_baselines/ActorCritic_Agent/* ../Multithreading_agent.ActorCritic_Agent import ActorCritic_Agent`

and then commit and push it back :-)

**Comment by BDonnot** [comment]
Oh and second comment:

When some dependencies are not met, you should avoid doing:
```python
except:
    print("You need the following package to train the A3C baseline")
    print(sys.exc_info())
    exit()
```
Indeed any attempt to load l2rpn-baselines with missing or incompatible dependencies will lead to a crash of the whole python script (with the `exit()` command) this is not the standard behaviour in python world.

The proper way is:
```python
try:
    import blablabla
    import blobloblo
    import ...
except ImportError as exc_:
     raise ImportError("NameOfTheBaseline impossible to load the required dependencies for training the model. The error was: \n {}".format(exc_))
```

And, if you want to be even more precise, in your `__init__.py` file you can do:
```python
import warnings
__all__ = ["NameOfTheBaseline", "evaluate"]  # this is mandatory and should not crash hopefully
from l2rpn_baselines.NameOfTheBaseline.NameOfTheBaseline import NameOfTheBaseline
from l2rpn_baselines.NameOfTheBaseline.evaluate import evaluate

# try to import the training module
try:
    from l2rpn_baselines.NameOfTheBaseline.train import train
    __all__.append("train")
except ImportError as exc_:
    warnings.warn("NameOfTheBaseline: impossible to load the \"train\" function because of missing dependencies. The error was: \n{}".format(exc_))

try:
    from l2rpn_baselines.NameOfTheBaseline.Runner import Runner
    __all__.append("Runner")
except ImportError as exc_:
    warnings.warn("NameOfTheBaseline: impossible to load the \"Runner\" class because of missing dependencies. The error was: \n{}".format(exc_))

etc.
```
This way people will still be able to use the function their environment allows.

Benjamin

**Comment by GonFreecsHxH** [comment]
Hi Benjamin,

Thank you so much for your help :) ! I fixed the issues you pointed out and I successfully was able to run the A3C agent on my local computer as part of l2rpnbaseline module. I committed the changes to this repo. Please have a look and let me know any further suggestions :) 

Also if you think the name for the baseline I came up with is again confusing then please suggest a good name :) please 

Kishan
